import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carnet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body
          className={`${inter.className} flex justify-center bg-zinc-50 dark:bg-zinc-950`}
        >
          <Provider>
            <main className="flex w-screen xl:w-10/12 h-screen flex-col">
              {children}
            </main>
          </Provider>
        </body>
    </html>
  );
}
